apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: train
  name: movies-deploy
spec:
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
      - name: cont1
        image: anitalluri00/flappybird
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: train
  ports:
    - port: 80
      targetPort: 80
