apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: flappybird
  name: flappybird-deploy
spec:
  selector:
    matchLabels:
      app: flappybird
  template:
    metadata:
      labels:
        app: flappybird
    spec:
      containers:
      - name: cont1
        image: anitalluri00/flappybird
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flappybird
spec:
  type: LoadBalancer
  selector:
    app: flappybird
  ports:
    - port: 80
      targetPort: 80
