apiVersion: apps/v1
kind: Deamonset
metadata:
  labels:
    app: flappy bird
  name: flappy-deploy
spec:
  selector:
    matchLabels:
      app: flappy
  template:
    metadata:
      labels:
        app: flappy
    spec:
      containers:
      - name: cont1
        image: anitalluri00/flappybird
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: flappy
  ports:
    - port: 80
      targetPort: 80
