apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: snakegame
  name: snake-deploy
spec:
  selector:
    matchLabels:
      app: snakegame
  template:
    metadata:
      labels:
        app: snakegame
    spec:
      containers:
      - name: cont1
        image: anitalluri00/hwd:latest
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: abc
spec:
  type: LoadBalancer
  selector:
    app: train
  ports:
    - port: 80
      targetPort: 80
